
const chauffeurs = [
    { legacy_id:1, full_name:'Rajesh Mehta', first_name:'Rajesh', age:42, experience_years:12, price_per_day:2200, total_trips_completed:1250,
      languages:['English','Hindi','Gujarati'], availability_status:'Available', is_top_chauffeur:true,
      profile_photo:'/images/chauffeurs/rajesh.png',
      preferred_car_types:['Luxury','Wedding'], uniform_style:'Premium Black Suit',
      driving_license_number:'DL-04-2010-*******', background_verified:true, police_verification_status:true,
      certifications:['Defensive Driving','VIP Protocol','First Aid'], specializations:['VIP Escort','Airport Transfers','Wedding Convoys'],
      bio:'LUXEDIVE\'s most decorated chauffeur with 12 years of service to India\'s business elite. Known for impeccable timing and zero-compromise attitude toward luxury.',
      driving_style:'Smooth & Calm',
      previous_work:[{company:'Taj Hotels – Private Fleet',period:'2012–2016'},{company:'Air India VIP Ground Division',period:'2016–2020'},{company:'LUXEDIVE Elite Division',period:'2020–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Mumbai',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Udaipur',duration:'2 Days',clientType:'Wedding'},{from:'Airport',to:'CM Secretariat',duration:'Half Day',clientType:'VIP'},{from:'Ahmedabad',to:'Jaipur',duration:'3 Days',clientType:'VIP'},{from:'Ahmedabad',to:'Surat',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Dwarka',duration:'2 Days',clientType:'Tourism'},{from:'Rajkot',to:'Ahmedabad',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Statue of Unity',duration:'1 Day',clientType:'Tourism'},{from:'Vadodara',to:'Ahmedabad',duration:'2 Hrs',clientType:'Business'},{from:'Airport',to:'ITC Narmada',duration:'1 Hr',clientType:'Airport'}]
    },
    { legacy_id:2, full_name:'Vikram Patel', first_name:'Vikram', age:35, experience_years:8, price_per_day:1500, total_trips_completed:850,
      languages:['Hindi','Gujarati','English'], availability_status:'Available',
      profile_photo:'https://images.unsplash.com/photo-1559418162-0d309d8d10a3?w=800&auto=format&fit=crop&q=60',
      preferred_car_types:['Wedding','Luxury'], uniform_style:'Formal Safari Suit',
      driving_license_number:'DL-01-2015-*******', background_verified:true, police_verification_status:true,
      certifications:['First Aid','Tourism Guide'], specializations:['Wedding Convoys','Airport Transfers','Family Events'],
      bio:'Go-to chauffeur for weddings and family events. Deep knowledge of Gujarati customs makes him ideal for celebratory occasions.',
      driving_style:'Professional & Precise',
      previous_work:[{company:'Ola Lux – Ahmedabad',period:'2016–2019'},{company:'IndiGo Elite Ground',period:'2019–2022'},{company:'LUXEDIVE Premium',period:'2022–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Udaipur (Wedding)',duration:'3 Days',clientType:'Wedding'},{from:'Airport',to:'City Hotel',duration:'45 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Dwarka',duration:'2 Days',clientType:'Tourism'},{from:'Ahmedabad',to:'Ambaji',duration:'1 Day',clientType:'Tourism'},{from:'Gandhinagar',to:'Ahmedabad',duration:'45 Mins',clientType:'Business'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'Business'},{from:'Surat Airport',to:'City',duration:'30 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Kutch',duration:'2 Days',clientType:'Tourism'},{from:'Airport',to:'Holiday Inn',duration:'40 Mins',clientType:'Airport'}]
    },
    { legacy_id:3, full_name:'Anil Shah', first_name:'Anil', age:29, experience_years:6, price_per_day:1200, total_trips_completed:600,
      languages:['English','Hindi','Marathi'], availability_status:'Available',
      profile_photo:'/images/chauffeurs/anil.png',
      preferred_car_types:['Sports','Exotic'], uniform_style:'Modern Formal',
      driving_license_number:'DL-12-2018-*******', background_verified:true, police_verification_status:true,
      certifications:['Defensive Driving'], specializations:['Sports Car Handling','City Tours','Night Events'],
      bio:'Most dynamic chauffeur in the fleet. Specializes in exotic and sports vehicles. Trained at IIMD Advanced Motorsport Academy.',
      driving_style:'Swift & Confident',
      previous_work:[{company:'Uber Premium – Mumbai',period:'2018–2020'},{company:'Myles Luxury Cars',period:'2020–2022'},{company:'LUXEDIVE Sports Division',period:'2022–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Surat',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Mumbai',duration:'2 Days',clientType:'Business'},{from:'Ahmedabad Nightlife',to:'Hotel',duration:'3 Hrs',clientType:'VIP'},{from:'Airport',to:'Ahmedabad',duration:'50 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Tourism'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'Business'},{from:'Ahmedabad',to:'Gandhinagar',duration:'30 Mins',clientType:'Business'},{from:'Ahmedabad',to:'Anand',duration:'1.5 Hrs',clientType:'Business'},{from:'Ahmedabad',to:'Mehsana',duration:'1 Hr',clientType:'Business'},{from:'Ahmedabad',to:'Girnar',duration:'1 Day',clientType:'Tourism'}]
    },
    { legacy_id:4, full_name:'Suresh Kumar', first_name:'Suresh', age:38, experience_years:10, price_per_day:900, total_trips_completed:750,
      languages:['Hindi','Gujarati'], availability_status:'Busy',
      profile_photo:'/images/chauffeurs/suresh.png',
      preferred_car_types:['Luxury'], uniform_style:'Formal',
      driving_license_number:'DL-09-2017-*******', background_verified:true, police_verification_status:true,
      certifications:['Defensive Driving','Elderly Care Transit'], specializations:['Family Trips','Medical Escort','Pilgrimage Routes'],
      bio:'Most trusted family-trip chauffeur. Specializes in comfortable long-distance travel for elderly clients and children.',
      driving_style:'Smooth & Calm',
      previous_work:[{company:'Sarthak Tours – Ahmedabad',period:'2014–2018'},{company:'MakeMyTrip Ground',period:'2018–2021'},{company:'LUXEDIVE Family Division',period:'2021–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Dwarka',duration:'3 Days',clientType:'Tourism'},{from:'Ahmedabad',to:'Somnath',duration:'2 Days',clientType:'Tourism'},{from:'Ahmedabad',to:'Ambaji',duration:'1 Day',clientType:'Tourism'},{from:'Ahmedabad',to:'Statue of Unity',duration:'1 Day',clientType:'Tourism'},{from:'Ahmedabad',to:'Palitana',duration:'2 Days',clientType:'Tourism'},{from:'Surat',to:'Ahmedabad',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'Business'},{from:'Airport',to:'City',duration:'45 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Mehsana',duration:'1 Hr',clientType:'Business'}]
    },
    { legacy_id:5, full_name:'Arjun Reddy', first_name:'Arjun', age:45, experience_years:15, price_per_day:2500, total_trips_completed:1500,
      languages:['English','Hindi','Telugu'], availability_status:'Available', is_top_chauffeur:true,
      profile_photo:'/images/chauffeurs/arjun.png',
      preferred_car_types:['Luxury','Exotic'], uniform_style:'Tactical Formal',
      driving_license_number:'DL-03-2005-*******', background_verified:true, police_verification_status:true,
      certifications:['Security Protocol','First Aid','Advanced Driving'], specializations:['VIP Security','Counter-Surveillance','Long-Range Missions'],
      bio:'Former NSG trainee turned luxury driver with 15 years of VIP escort experience for Cabinet ministers and corporate CEOs.',
      driving_style:'Luxury & Refined',
      previous_work:[{company:'NSG Training Corps',period:'2005–2010'},{company:'Oberoi Hotels – VIP Fleet',period:'2010–2019'},{company:'LUXEDIVE Security Division',period:'2019–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Mumbai (VIP)',duration:'1 Day',clientType:'VIP'},{from:'Airport',to:'Secretariat',duration:'1 Hr',clientType:'VIP'},{from:'Ahmedabad',to:'Jaipur',duration:'2 Days',clientType:'VIP'},{from:'Ahmedabad',to:'Delhi',duration:'3 Days',clientType:'Business'},{from:'Ahmedabad',to:'Udaipur',duration:'2 Days',clientType:'VIP'},{from:'Airport',to:'The Leela',duration:'40 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Surat',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'},{from:'Surat',to:'Ahmedabad',duration:'1 Day',clientType:'VIP'},{from:'Ahmedabad',to:'Jodhpur',duration:'3 Days',clientType:'VIP'}]
    },
    { legacy_id:6, full_name:'Mohan Das', first_name:'Mohan', age:52, experience_years:25, price_per_day:1800, total_trips_completed:3000,
      languages:['English','Hindi','Gujarati'], availability_status:'On Leave', is_top_chauffeur:true,
      profile_photo:'/images/chauffeurs/mohan.png',
      preferred_car_types:['Luxury'], uniform_style:'Classic Chauffeur',
      driving_license_number:'DL-01-1995-*******', background_verified:true, police_verification_status:true,
      certifications:['Master Driver','VIP Protocol','First Aid'], specializations:['Diplomatic Escort','VVIP Protocol','Government Fleet'],
      bio:'Living legend of Indian luxury driving. 3,000+ trips over 25 years. Personal commendation from the Government of Gujarat.',
      driving_style:'Luxury & Refined',
      previous_work:[{company:'Gujarat Government – CM Convoy',period:'1998–2007'},{company:'ITC Hotels – Master Chauffeur',period:'2007–2018'},{company:'LUXEDIVE – Chief Ambassador',period:'2018–Present'}],
      top_trips:[{from:'Gandhinagar',to:'New Delhi',duration:'2 Days',clientType:'VIP'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'VIP'},{from:'Airport',to:'Raj Bhavan',duration:'1 Hr',clientType:'VIP'},{from:'Ahmedabad',to:'Udaipur',duration:'2 Days',clientType:'VIP'},{from:'Ahmedabad',to:'Jaipur',duration:'2 Days',clientType:'Business'},{from:'Ahmedabad',to:'Surat',duration:'1 Day',clientType:'Business'},{from:'Gandhinagar',to:'Airport',duration:'30 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'VIP'},{from:'Ahmedabad',to:'Dwarka',duration:'2 Days',clientType:'VIP'},{from:'Ahmedabad',to:'Mumbai',duration:'1 Day',clientType:'VIP'}]
    },
    { legacy_id:7, full_name:'Dinesh Solanki', first_name:'Dinesh', age:34, experience_years:7, price_per_day:1100, total_trips_completed:420,
      languages:['Hindi','Gujarati'], availability_status:'Available',
      profile_photo:'/images/chauffeurs/dinesh.png',
      preferred_car_types:['Luxury'], uniform_style:'Business Formal',
      driving_license_number:'DL-07-2017-*******', background_verified:true, police_verification_status:true,
      certifications:['Defensive Driving'], specializations:['Corporate Transfers','Airport Pickups','Highway Trips'],
      bio:'Reliable and punctual chauffeur with 7 years of corporate transport experience across Gujarat.',
      driving_style:'Professional & Precise',
      previous_work:[{company:'Zoom Car – Ahmedabad',period:'2017–2020'},{company:'Orix Fleet Services',period:'2020–2023'},{company:'LUXEDIVE',period:'2023–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Gandhinagar',duration:'30 Mins',clientType:'Business'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'},{from:'Airport',to:'Hotel',duration:'1 Hr',clientType:'Airport'},{from:'Ahmedabad',to:'Surat',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'Business'},{from:'Ahmedabad',to:'Mehsana',duration:'1 Hr',clientType:'Business'},{from:'Surat',to:'Ahmedabad',duration:'1 Day',clientType:'Business'},{from:'Rajkot',to:'Ahmedabad',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Anand',duration:'1 Hr',clientType:'Business'},{from:'Airport',to:'City Center',duration:'50 Mins',clientType:'Airport'}]
    },
    { legacy_id:8, full_name:'Kamlesh Rathod', first_name:'Kamlesh', age:40, experience_years:9, price_per_day:1300, total_trips_completed:560,
      languages:['Hindi','Gujarati','English'], availability_status:'Available',
      profile_photo:'https://images.unsplash.com/photo-1712130126754-009c33690ee3?w=800&auto=format&fit=crop&q=60',
      preferred_car_types:['Luxury','Wedding'], uniform_style:'Formal Safari',
      driving_license_number:'DL-05-2015-*******', background_verified:true, police_verification_status:true,
      certifications:['First Aid','Wedding Logistics'], specializations:['Wedding Convoys','VIP Transfers','Event Logistics'],
      bio:'Specialist in wedding event logistics with experience managing large convoy operations across Rajasthan and Gujarat.',
      driving_style:'Smooth & Calm',
      previous_work:[{company:'Rajputana Limos – Jaipur',period:'2015–2019'},{company:'Ahmedabad Event Cars',period:'2019–2023'},{company:'LUXEDIVE',period:'2023–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Udaipur (Baraat)',duration:'2 Days',clientType:'Wedding'},{from:'Ahmedabad',to:'Jaipur',duration:'2 Days',clientType:'Wedding'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'},{from:'Airport',to:'Hotel',duration:'45 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'Business'},{from:'Surat',to:'Ahmedabad',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Ambaji',duration:'1 Day',clientType:'Tourism'},{from:'Ahmedabad',to:'Dwarka',duration:'2 Days',clientType:'Tourism'},{from:'Gandhinagar',to:'Ahmedabad',duration:'45 Mins',clientType:'Business'},{from:'Ahmedabad',to:'Kutch',duration:'2 Days',clientType:'Tourism'}]
    },
    { legacy_id:9, full_name:'Bhavesh Parmar', first_name:'Bhavesh', age:31, experience_years:5, price_per_day:800, total_trips_completed:280,
      languages:['Gujarati','Hindi'], availability_status:'Available',
      profile_photo:'https://images.unsplash.com/photo-1558222218-b7b54eede3f3?w=800&auto=format&fit=crop&q=60',
      preferred_car_types:['Luxury'], uniform_style:'Casual Formal',
      driving_license_number:'DL-11-2019-*******', background_verified:true, police_verification_status:true,
      certifications:['Defensive Driving'], specializations:['City Tours','Short Transfers','Outstation Trips'],
      bio:'Young professional with a knack for navigating Ahmedabad\'s complex road network efficiently. Great with first-time luxury car clients.',
      driving_style:'Swift & Confident',
      previous_work:[{company:'Rapido Captain – Ahmedabad',period:'2019–2021'},{company:'BluSmart EV Fleet',period:'2021–2023'},{company:'LUXEDIVE',period:'2023–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Gandhinagar',duration:'30 Mins',clientType:'Business'},{from:'Airport',to:'City',duration:'1 Hr',clientType:'Airport'},{from:'Ahmedabad',to:'Anand',duration:'1 Hr',clientType:'Business'},{from:'Ahmedabad',to:'Nadiad',duration:'45 Mins',clientType:'Business'},{from:'City Tour',to:'Ahmedabad',duration:'3 Hrs',clientType:'Tourism'},{from:'Ahmedabad',to:'Surat',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Mehsana',duration:'1 Hr',clientType:'Business'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'Business'},{from:'Rajkot Airport',to:'City',duration:'30 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'}]
    },
    { legacy_id:10, full_name:'Nitin Joshi', first_name:'Nitin', age:39, experience_years:11, price_per_day:1600, total_trips_completed:900,
      languages:['English','Hindi','Gujarati'], availability_status:'Available',
      profile_photo:'https://media.istockphoto.com/id/2165571969/photo/asian-businessman-big-toothy-smile-studio-isolated-portrait-confident-professional-office.webp?a=1&b=1&s=612x612&w=0&k=20&c=shDtTV_1-bzmeSGb8zPse8CDQAc2TLCAsSbaQopNZ8Q=',
      preferred_car_types:['Luxury','Exotic'], uniform_style:'Premium Formal',
      driving_license_number:'DL-02-2013-*******', background_verified:true, police_verification_status:true,
      certifications:['Advanced Driving','VIP Protocol'], specializations:['Luxury Fleet Management','Long Range Travel'],
      bio:'Experienced professional specializing in long-distance luxury journeys across western India. Known for comfort optimization on extended trips.',
      driving_style:'Luxury & Refined',
      previous_work:[{company:'Hertz Luxury – Ahmedabad',period:'2013–2017'},{company:'MMS Travels VIP',period:'2017–2022'},{company:'LUXEDIVE',period:'2022–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Mumbai',duration:'2 Days',clientType:'Business'},{from:'Ahmedabad',to:'Jaipur',duration:'2 Days',clientType:'VIP'},{from:'Ahmedabad',to:'Delhi',duration:'3 Days',clientType:'Business'},{from:'Ahmedabad',to:'Udaipur',duration:'2 Days',clientType:'Tourism'},{from:'Ahmedabad',to:'Jodhpur',duration:'2 Days',clientType:'VIP'},{from:'Ahmedabad',to:'Somnath',duration:'2 Days',clientType:'Tourism'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Surat',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Dwarka',duration:'2 Days',clientType:'Tourism'},{from:'Airport',to:'Hotel',duration:'1 Hr',clientType:'Airport'}]
    },
    { legacy_id:11, full_name:'Hardik Trivedi', first_name:'Hardik', age:27, experience_years:4, price_per_day:700, total_trips_completed:180,
      languages:['Gujarati','Hindi'], availability_status:'Available',
      profile_photo:'https://images.unsplash.com/photo-1714237447344-21773efd1d56?w=800&auto=format&fit=crop&q=60',
      preferred_car_types:['Luxury'], uniform_style:'Smart Casual Formal',
      driving_license_number:'DL-08-2020-*******', background_verified:true, police_verification_status:false,
      certifications:['Defensive Driving'], specializations:['City Transfers','Airport Pickups','Day Hire'],
      bio:'Emerging chauffeur known for warm hospitality and local area expertise across Ahmedabad\'s key business districts.',
      driving_style:'Professional & Precise',
      previous_work:[{company:'Ola – Ahmedabad',period:'2020–2022'},{company:'LUXEDIVE (Trainee)',period:'2022–Present'}],
      top_trips:[{from:'Airport',to:'City',duration:'1 Hr',clientType:'Airport'},{from:'Ahmedabad',to:'Gandhinagar',duration:'30 Mins',clientType:'Business'},{from:'Ahmedabad',to:'Anand',duration:'1 Hr',clientType:'Business'},{from:'Ahmedabad',to:'Nadiad',duration:'45 Mins',clientType:'Business'},{from:'City Tour',to:'Ahmedabad',duration:'4 Hrs',clientType:'Tourism'},{from:'Ahmedabad',to:'Mehsana',duration:'1 Hr',clientType:'Business'},{from:'Ahmedabad',to:'Sanand',duration:'30 Mins',clientType:'Business'},{from:'Airport',to:'Hotel',duration:'50 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'Business'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'}]
    },
    { legacy_id:12, full_name:'Kalpesh Desai', first_name:'Kalpesh', age:43, experience_years:13, price_per_day:1700, total_trips_completed:1100,
      languages:['English','Gujarati','Hindi'], availability_status:'Available', is_top_chauffeur:true,
      profile_photo:'https://images.unsplash.com/photo-1763610452494-e4c2acc57690?q=80&w=800&auto=format&fit=crop',
      preferred_car_types:['Luxury','Wedding'], uniform_style:'Classic Black Formal',
      driving_license_number:'DL-03-2011-*******', background_verified:true, police_verification_status:true,
      certifications:['Defensive Driving','First Aid','VIP Protocol'], specializations:['Corporate Accounts','Airport Transfers','VIP Escort'],
      bio:'Senior chauffeur with 13 years of elite service. Client retention rate exceeds 90% — passengers become regulars after the first ride.',
      driving_style:'Smooth & Calm',
      previous_work:[{company:'Marriott Hotels Fleet',period:'2011–2016'},{company:'Corporate Concierge India',period:'2016–2021'},{company:'LUXEDIVE',period:'2021–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Mumbai',duration:'1 Day',clientType:'Business'},{from:'Airport',to:'Marriott',duration:'40 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Udaipur',duration:'2 Days',clientType:'VIP'},{from:'Ahmedabad',to:'Jaipur',duration:'2 Days',clientType:'Business'},{from:'Ahmedabad',to:'Surat',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'Business'},{from:'Gandhinagar',to:'Ahmedabad',duration:'45 Mins',clientType:'Business'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Statue of Unity',duration:'1 Day',clientType:'Tourism'},{from:'Airport',to:'Hotel',duration:'1 Hr',clientType:'Airport'}]
    },
    { legacy_id:13, full_name:'Mukesh Agarwal', first_name:'Mukesh', age:48, experience_years:18, price_per_day:2000, total_trips_completed:2100,
      languages:['Hindi','English'], availability_status:'Available', is_top_chauffeur:true,
      profile_photo:'https://images.unsplash.com/photo-1618077360395-f3068be8e001?w=800&auto=format&fit=crop&q=60',
      preferred_car_types:['Luxury','Exotic'], uniform_style:'Classic Chauffeur',
      driving_license_number:'DL-06-2006-*******', background_verified:true, police_verification_status:true,
      certifications:['Master Driver','Advanced Driving','VIP Protocol'], specializations:['VIP Handling','International Clients'],
      bio:'18-year veteran with specialization in international clientele. Has driven visiting delegations at three Vibrant Gujarat Summits.',
      driving_style:'Luxury & Refined',
      previous_work:[{company:'Hyatt Hotels – VIP Fleet',period:'2006–2014'},{company:'Gujarat Tourism Board',period:'2014–2020'},{company:'LUXEDIVE',period:'2020–Present'}],
      top_trips:[{from:'Airport',to:'Vibrant Gujarat Venue',duration:'1 Hr',clientType:'VIP'},{from:'Ahmedabad',to:'Delhi',duration:'3 Days',clientType:'VIP'},{from:'Ahmedabad',to:'Mumbai',duration:'1 Day',clientType:'VIP'},{from:'Ahmedabad',to:'Jaipur',duration:'2 Days',clientType:'VIP'},{from:'Ahmedabad',to:'Udaipur',duration:'2 Days',clientType:'Tourism'},{from:'Gandhinagar',to:'Airport',duration:'45 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Surat',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Somnath',duration:'2 Days',clientType:'Tourism'},{from:'Airport',to:'Hotel',duration:'50 Mins',clientType:'Airport'}]
    },
    { legacy_id:14, full_name:'Jigar Pandya', first_name:'Jigar', age:33, experience_years:6, price_per_day:950, total_trips_completed:320,
      languages:['Gujarati','Hindi','English'], availability_status:'Busy',
      profile_photo:'https://images.unsplash.com/photo-1552571072-0eadf8e3953c?w=800&auto=format&fit=crop&q=60',
      preferred_car_types:['Luxury'], uniform_style:'Business Casual Formal',
      driving_license_number:'DL-04-2018-*******', background_verified:true, police_verification_status:true,
      certifications:['Defensive Driving'], specializations:['City Tours','Heritage Routes','Airport Transfers'],
      bio:'Popular city guide and chauffeur rolled into one. Clients love his commentary on Ahmedabad\'s heritage and modern landmarks during drives.',
      driving_style:'Professional & Precise',
      previous_work:[{company:'Gujarat Tourism Dept.',period:'2018–2021'},{company:'LUXEDIVE',period:'2021–Present'}],
      top_trips:[{from:'Ahmedabad Heritage Walk',to:'City',duration:'3 Hrs',clientType:'Tourism'},{from:'Airport',to:'Hotel',duration:'1 Hr',clientType:'Airport'},{from:'Ahmedabad',to:'Modhera',duration:'1 Day',clientType:'Tourism'},{from:'Ahmedabad',to:'Patan',duration:'1 Day',clientType:'Tourism'},{from:'Ahmedabad',to:'Gandhinagar',duration:'30 Mins',clientType:'Business'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'Business'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Mehsana',duration:'1 Hr',clientType:'Business'},{from:'Airport',to:'City',duration:'45 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Anand',duration:'1 Hr',clientType:'Business'}]
    },
    { legacy_id:15, full_name:'Tejas Kapadia', first_name:'Tejas', age:30, experience_years:5, price_per_day:850, total_trips_completed:240,
      languages:['English','Gujarati'], availability_status:'Available',
      profile_photo:'https://plus.unsplash.com/premium_photo-1663076401064-a5fec5be2948?w=800&auto=format&fit=crop&q=60',
      preferred_car_types:['Sports','Exotic'], uniform_style:'Modern Sleek Formal',
      driving_license_number:'DL-09-2019-*******', background_verified:true, police_verification_status:true,
      certifications:['Defensive Driving'], specializations:['Sports Cars','Performance Driving','Night Events'],
      bio:'Adrenaline-aware chauffeur who blends speed consciousness with absolute safety. Ideal for sports car hirers seeking a premium experience.',
      driving_style:'Swift & Confident',
      previous_work:[{company:'Prestige Motorworks',period:'2019–2022'},{company:'LUXEDIVE Sports',period:'2022–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Surat',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'Business'},{from:'Night Drive',to:'Ahmedabad',duration:'2 Hrs',clientType:'VIP'},{from:'Airport',to:'Hotel',duration:'1 Hr',clientType:'Airport'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Anand',duration:'1 Hr',clientType:'Business'},{from:'Ahmedabad',to:'Gandhinagar',duration:'30 Mins',clientType:'Business'},{from:'Ahmedabad',to:'Mumbai',duration:'2 Days',clientType:'Business'},{from:'City Tour',to:'Ahmedabad',duration:'3 Hrs',clientType:'Tourism'},{from:'Airport',to:'City',duration:'50 Mins',clientType:'Airport'}]
    },
    { legacy_id:16, full_name:'Darshan Naik', first_name:'Darshan', age:36, experience_years:8, price_per_day:1050, total_trips_completed:490,
      languages:['Hindi','Gujarati','Telugu'], availability_status:'Available',
      profile_photo:'https://images.unsplash.com/photo-1654279511005-eb0531f49dce?w=800&auto=format&fit=crop&q=60',
      preferred_car_types:['Luxury'], uniform_style:'Formal',
      driving_license_number:'DL-10-2016-*******', background_verified:true, police_verification_status:true,
      certifications:['First Aid','Defensive Driving'], specializations:['Long Distance','Highway Safety'],
      bio:'Calm demeanor, zero accidents in 8+ years. Preferred by repeat clients for his reliability on extended highway journeys.',
      driving_style:'Smooth & Calm',
      previous_work:[{company:'GSRTC Premium Coach',period:'2016–2019'},{company:'IntrCity Smart Bus',period:'2019–2022'},{company:'LUXEDIVE',period:'2022–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Surat',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'Business'},{from:'Ahmedabad',to:'Mehsana',duration:'1 Hr',clientType:'Business'},{from:'Ahmedabad',to:'Dwarka',duration:'2 Days',clientType:'Tourism'},{from:'Ahmedabad',to:'Somnath',duration:'2 Days',clientType:'Tourism'},{from:'Airport',to:'City',duration:'1 Hr',clientType:'Airport'},{from:'Ahmedabad',to:'Mumbai',duration:'2 Days',clientType:'Business'},{from:'Rajkot',to:'Ahmedabad',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Jamnagar',duration:'1 Day',clientType:'Business'}]
    },
    { legacy_id:17, full_name:'Vishal Rana', first_name:'Vishal', age:44, experience_years:14, price_per_day:1900, total_trips_completed:1300,
      languages:['English','Hindi'], availability_status:'Available', is_top_chauffeur:true,
      profile_photo:'https://images.unsplash.com/photo-1747913485453-42696ca5b510?w=800&auto=format&fit=crop&q=60',
      preferred_car_types:['Luxury','Exotic'], uniform_style:'Premium Black Suit',
      driving_license_number:'DL-01-2010-*******', background_verified:true, police_verification_status:true,
      certifications:['Advanced Driving','VIP Protocol','Security Protocol'], specializations:['VIP Security','Corporate Events','International Guests'],
      bio:'Ex-hotel security and luxury fleet manager with 14 years of impeccable service. Combines discretion with professionalism.',
      driving_style:'Luxury & Refined',
      previous_work:[{company:'Le Meridien Hotels – Security',period:'2010–2015'},{company:'KPMG Corporate Fleet',period:'2015–2021'},{company:'LUXEDIVE',period:'2021–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Mumbai',duration:'1 Day',clientType:'VIP'},{from:'Airport',to:'Corporate HQ',duration:'1 Hr',clientType:'Business'},{from:'Ahmedabad',to:'Jaipur',duration:'2 Days',clientType:'VIP'},{from:'Ahmedabad',to:'Delhi',duration:'3 Days',clientType:'Business'},{from:'Ahmedabad',to:'Udaipur',duration:'2 Days',clientType:'VIP'},{from:'Airport',to:'Hotel',duration:'45 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Surat',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'},{from:'Gandhinagar',to:'Airport',duration:'40 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Somnath',duration:'2 Days',clientType:'Tourism'}]
    },
    { legacy_id:18, full_name:'Rohan Choksi', first_name:'Rohan', age:28, experience_years:3, price_per_day:650, total_trips_completed:120,
      languages:['English','Gujarati'], availability_status:'Available',
      profile_photo:'https://media.istockphoto.com/id/1162254186/photo/indian-businessman.webp?a=1&b=1&s=612x612&w=0&k=20&c=J9hMQKL8fq1wIOxvdAKTcYxc664gEatv6y2L6o7rvEg=',
      preferred_car_types:['Luxury'], uniform_style:'Smart Casual Formal',
      driving_license_number:'DL-06-2021-*******', background_verified:true, police_verification_status:false,
      certifications:['Defensive Driving'], specializations:['City Transfers','Short Distance','Airport Pickups'],
      bio:'One of LUXEDIVE\'s newest recruits, Rohan brings enthusiasm and modern driving techniques. Best suited for city and short-distance rides.',
      driving_style:'Swift & Confident',
      previous_work:[{company:'Uber – Ahmedabad',period:'2021–2023'},{company:'LUXEDIVE (Junior)',period:'2023–Present'}],
      top_trips:[{from:'Airport',to:'City',duration:'1 Hr',clientType:'Airport'},{from:'Ahmedabad',to:'Gandhinagar',duration:'30 Mins',clientType:'Business'},{from:'Ahmedabad',to:'Anand',duration:'1 Hr',clientType:'Business'},{from:'City Tour',to:'Ahmedabad',duration:'2 Hrs',clientType:'Tourism'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'Business'},{from:'Ahmedabad',to:'Sanand',duration:'30 Mins',clientType:'Business'},{from:'Airport',to:'Hotel',duration:'50 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Mehsana',duration:'1 Hr',clientType:'Business'},{from:'Ahmedabad',to:'Nadiad',duration:'45 Mins',clientType:'Business'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'}]
    },
    { legacy_id:19, full_name:'Nilesh Vaghela', first_name:'Nilesh', age:41, experience_years:12, price_per_day:1400, total_trips_completed:820,
      languages:['Gujarati','Hindi','English'], availability_status:'Available',
      profile_photo:'https://images.unsplash.com/photo-1676743217690-fb7bb4f20544?w=800&auto=format&fit=crop&q=60',
      preferred_car_types:['Luxury','Wedding'], uniform_style:'Traditional Formal',
      driving_license_number:'DL-07-2012-*******', background_verified:true, police_verification_status:true,
      certifications:['Defensive Driving','First Aid'], specializations:['Pilgrimage Routes','Wedding Events'],
      bio:'Deeply knowledgeable about pilgrimage routes across Gujarat and Rajasthan. Preferred choice for religious trips and family functions.',
      driving_style:'Smooth & Calm',
      previous_work:[{company:'Saurashtra Tours',period:'2012–2016'},{company:'Gujarat Darshan',period:'2016–2021'},{company:'LUXEDIVE',period:'2021–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Dwarka',duration:'2 Days',clientType:'Tourism'},{from:'Ahmedabad',to:'Somnath',duration:'2 Days',clientType:'Tourism'},{from:'Ahmedabad',to:'Ambaji',duration:'1 Day',clientType:'Tourism'},{from:'Ahmedabad',to:'Palitana',duration:'2 Days',clientType:'Tourism'},{from:'Ahmedabad',to:'Shamlaji',duration:'1 Day',clientType:'Tourism'},{from:'Ahmedabad',to:'Girnar',duration:'1 Day',clientType:'Tourism'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'Business'},{from:'Airport',to:'Hotel',duration:'45 Mins',clientType:'Airport'},{from:'Ahmedabad',to:'Udaipur (Wedding)',duration:'2 Days',clientType:'Wedding'}]
    },
    { legacy_id:20, full_name:'Sanjay Sharma', first_name:'Sanjay', age:37, experience_years:9, price_per_day:1250, total_trips_completed:640,
      languages:['Hindi','English','Punjabi'], availability_status:'Available',
      profile_photo:'https://media.istockphoto.com/id/1162520281/photo/portrait-of-a-young-indian-successful-businessman-wearing-suit-and-spectacles.webp?a=1&b=1&s=612x612&w=0&k=20&c=xFA3oCo8UBx1ieLkMJBWyQT7oZOlbsukG2i30G856H8=',
      preferred_car_types:['Luxury','Exotic'], uniform_style:'Premium Formal',
      driving_license_number:'DL-03-2015-*******', background_verified:true, police_verification_status:true,
      certifications:['Defensive Driving','Advanced Driving'], specializations:['North India Routes','VIP Transfers'],
      bio:'Cross-country specialist with extensive knowledge of NH-48 and NH-27 corridors. Popular for Ahmedabad–Delhi and Ahmedabad–Mumbai runs.',
      driving_style:'Professional & Precise',
      previous_work:[{company:'Zoomcar Fleet Delhi',period:'2015–2018'},{company:'Revv Luxury – Pan India',period:'2018–2022'},{company:'LUXEDIVE',period:'2022–Present'}],
      top_trips:[{from:'Ahmedabad',to:'Delhi',duration:'3 Days',clientType:'Business'},{from:'Ahmedabad',to:'Mumbai',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Jaipur',duration:'2 Days',clientType:'Business'},{from:'Ahmedabad',to:'Udaipur',duration:'2 Days',clientType:'Tourism'},{from:'Ahmedabad',to:'Jodhpur',duration:'2 Days',clientType:'VIP'},{from:'Ahmedabad',to:'Surat',duration:'1 Day',clientType:'Business'},{from:'Airport',to:'Hotel',duration:'1 Hr',clientType:'Airport'},{from:'Ahmedabad',to:'Rajkot',duration:'1 Day',clientType:'Business'},{from:'Ahmedabad',to:'Vadodara',duration:'2 Hrs',clientType:'Business'},{from:'Ahmedabad',to:'Dwarka',duration:'2 Days',clientType:'Tourism'}]
    },
];

import fs from 'fs';

let sql = "INSERT INTO chauffeurs (legacy_id, full_name, first_name, profile_photo, age, experience_years, total_trips_completed, price_per_day, languages, availability_status, is_top_chauffeur, bio, driving_style, specializations, uniform_style, certifications, background_verified, police_verification_status, driving_license_number, top_trips, previous_work, preferred_car_types) VALUES\n";

const rows = chauffeurs.map(c => {
    const isTop = c.is_top_chauffeur === true;
    return `(${c.legacy_id}, '${c.full_name.replace(/'/g, "''")}', '${c.first_name.replace(/'/g, "''")}', '${c.profile_photo}', ${c.age}, ${c.experience_years}, ${c.total_trips_completed}, ${c.price_per_day}, ARRAY[${c.languages.map(l => `'${l}'`).join(',')}], '${c.availability_status}', ${isTop}, '${c.bio.replace(/'/g, "''")}', '${c.driving_style.replace(/'/g, "''")}', ARRAY[${c.specializations.map(s => `'${s.replace(/'/g, "''")}'`).join(',')}], '${c.uniform_style.replace(/'/g, "''")}', ARRAY[${c.certifications.map(ct => `'${ct.replace(/'/g, "''")}'`).join(',')}], ${c.background_verified === true}, ${c.police_verification_status === true}, '${c.driving_license_number}', '${JSON.stringify(c.top_trips || []).replace(/'/g, "''")}'::jsonb, '${JSON.stringify(c.previous_work || []).replace(/'/g, "''")}'::jsonb, ARRAY[${(c.preferred_car_types || []).map(p => `'${p}'`).join(',')}])`;
});

sql += rows.join(",\n") + "\nON CONFLICT (legacy_id) DO UPDATE SET is_top_chauffeur = EXCLUDED.is_top_chauffeur, price_per_day = EXCLUDED.price_per_day, availability_status = EXCLUDED.availability_status;";

fs.writeFileSync('insert_chauffeurs.sql', sql, 'utf8');
console.log("Done");
